
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_HealthManager1_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_bluez_HealthManager1_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class HealthManager1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.HealthManager1";

protected:
    HealthManager1_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    HealthManager1_adaptor(const HealthManager1_adaptor&) = delete;
    HealthManager1_adaptor& operator=(const HealthManager1_adaptor&) = delete;
    HealthManager1_adaptor(HealthManager1_adaptor&&) = delete;
    HealthManager1_adaptor& operator=(HealthManager1_adaptor&&) = delete;

    ~HealthManager1_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("CreateApplication").withInputParamNames("config").withOutputParamNames("application").implementedAs([this](const std::map<std::string, sdbus::Variant>& config){ return this->CreateApplication(config); })
                          , sdbus::registerMethod("DestroyApplication").withInputParamNames("application").implementedAs([this](const sdbus::ObjectPath& application){ return this->DestroyApplication(application); })
                          ).forInterface(INTERFACE_NAME);
    }

private:
    virtual sdbus::ObjectPath CreateApplication(const std::map<std::string, sdbus::Variant>& config) = 0;
    virtual void DestroyApplication(const sdbus::ObjectPath& application) = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
