
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_LEAdvertisingManager1_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_bluez_LEAdvertisingManager1_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class LEAdvertisingManager1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.LEAdvertisingManager1";

protected:
    LEAdvertisingManager1_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    LEAdvertisingManager1_adaptor(const LEAdvertisingManager1_adaptor&) = delete;
    LEAdvertisingManager1_adaptor& operator=(const LEAdvertisingManager1_adaptor&) = delete;
    LEAdvertisingManager1_adaptor(LEAdvertisingManager1_adaptor&&) = delete;
    LEAdvertisingManager1_adaptor& operator=(LEAdvertisingManager1_adaptor&&) = delete;

    ~LEAdvertisingManager1_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("RegisterAdvertisement").withInputParamNames("advertisement", "options").implementedAs([this](const sdbus::ObjectPath& advertisement, const std::map<std::string, sdbus::Variant>& options){ return this->RegisterAdvertisement(advertisement, options); })
                          , sdbus::registerMethod("UnregisterAdvertisement").withInputParamNames("service").implementedAs([this](const sdbus::ObjectPath& service){ return this->UnregisterAdvertisement(service); })
                          , sdbus::registerProperty("ActiveInstances").withGetter([this](){ return this->ActiveInstances(); })
                          , sdbus::registerProperty("SupportedInstances").withGetter([this](){ return this->SupportedInstances(); })
                          , sdbus::registerProperty("SupportedIncludes").withGetter([this](){ return this->SupportedIncludes(); })
                          , sdbus::registerProperty("SupportedSecondaryChannels").withGetter([this](){ return this->SupportedSecondaryChannels(); })
                          ).forInterface(INTERFACE_NAME);
    }

private:
    virtual void RegisterAdvertisement(const sdbus::ObjectPath& advertisement, const std::map<std::string, sdbus::Variant>& options) = 0;
    virtual void UnregisterAdvertisement(const sdbus::ObjectPath& service) = 0;

private:
    virtual uint8_t ActiveInstances() = 0;
    virtual uint8_t SupportedInstances() = 0;
    virtual std::vector<std::string> SupportedIncludes() = 0;
    virtual std::vector<std::string> SupportedSecondaryChannels() = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
