
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_Agent1_proxy_h__proxy__H__
#define __sdbuscpp__sdbus_org_bluez_Agent1_proxy_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class Agent1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.Agent1";

protected:
    Agent1_proxy(sdbus::IProxy& proxy)
        : m_proxy(proxy)
    {
    }

    Agent1_proxy(const Agent1_proxy&) = delete;
    Agent1_proxy& operator=(const Agent1_proxy&) = delete;
    Agent1_proxy(Agent1_proxy&&) = delete;
    Agent1_proxy& operator=(Agent1_proxy&&) = delete;

    ~Agent1_proxy() = default;

    void registerProxy()
    {
    }

public:
    void Release()
    {
        m_proxy.callMethod("Release").onInterface(INTERFACE_NAME);
    }

    std::string RequestPinCode(const sdbus::ObjectPath& device)
    {
        std::string result;
        m_proxy.callMethod("RequestPinCode").onInterface(INTERFACE_NAME).withArguments(device).storeResultsTo(result);
        return result;
    }

    uint32_t RequestPasskey(const sdbus::ObjectPath& device)
    {
        uint32_t result;
        m_proxy.callMethod("RequestPasskey").onInterface(INTERFACE_NAME).withArguments(device).storeResultsTo(result);
        return result;
    }

    void DisplayPinCode(const sdbus::ObjectPath& device, const std::string& pincode)
    {
        m_proxy.callMethod("DisplayPinCode").onInterface(INTERFACE_NAME).withArguments(device, pincode);
    }

    void RequestConfirmation(const sdbus::ObjectPath& device, const uint32_t& passkey)
    {
        m_proxy.callMethod("RequestConfirmation").onInterface(INTERFACE_NAME).withArguments(device, passkey);
    }

    void RequestAuthorization(const sdbus::ObjectPath& device)
    {
        m_proxy.callMethod("RequestAuthorization").onInterface(INTERFACE_NAME).withArguments(device);
    }

    void AuthorizeService(const sdbus::ObjectPath& device, const std::string& uuid)
    {
        m_proxy.callMethod("AuthorizeService").onInterface(INTERFACE_NAME).withArguments(device, uuid);
    }

    void Cancel()
    {
        m_proxy.callMethod("Cancel").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy& m_proxy;
};

}} // namespaces

#endif
