
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_ProfileManager1_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_bluez_ProfileManager1_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class ProfileManager1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.ProfileManager1";

protected:
    ProfileManager1_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    ProfileManager1_adaptor(const ProfileManager1_adaptor&) = delete;
    ProfileManager1_adaptor& operator=(const ProfileManager1_adaptor&) = delete;
    ProfileManager1_adaptor(ProfileManager1_adaptor&&) = delete;
    ProfileManager1_adaptor& operator=(ProfileManager1_adaptor&&) = delete;

    ~ProfileManager1_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("RegisterProfile").withInputParamNames("profile", "UUID", "options").implementedAs([this](const sdbus::ObjectPath& profile, const std::string& UUID, const std::map<std::string, sdbus::Variant>& options){ return this->RegisterProfile(profile, UUID, options); })
                          , sdbus::registerMethod("UnregisterProfile").withInputParamNames("profile").implementedAs([this](const sdbus::ObjectPath& profile){ return this->UnregisterProfile(profile); })
                          ).forInterface(INTERFACE_NAME);
    }

private:
    virtual void RegisterProfile(const sdbus::ObjectPath& profile, const std::string& UUID, const std::map<std::string, sdbus::Variant>& options) = 0;
    virtual void UnregisterProfile(const sdbus::ObjectPath& profile) = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
