
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_Media1_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_bluez_Media1_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class Media1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.Media1";

protected:
    Media1_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    Media1_adaptor(const Media1_adaptor&) = delete;
    Media1_adaptor& operator=(const Media1_adaptor&) = delete;
    Media1_adaptor(Media1_adaptor&&) = delete;
    Media1_adaptor& operator=(Media1_adaptor&&) = delete;

    ~Media1_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("RegisterEndpoint").withInputParamNames("endpoint", "properties").implementedAs([this](const sdbus::ObjectPath& endpoint, const std::map<std::string, sdbus::Variant>& properties){ return this->RegisterEndpoint(endpoint, properties); })
                          , sdbus::registerMethod("UnregisterEndpoint").withInputParamNames("endpoint").implementedAs([this](const sdbus::ObjectPath& endpoint){ return this->UnregisterEndpoint(endpoint); })
                          , sdbus::registerMethod("RegisterPlayer").withInputParamNames("player", "properties").implementedAs([this](const sdbus::ObjectPath& player, const std::map<std::string, sdbus::Variant>& properties){ return this->RegisterPlayer(player, properties); })
                          , sdbus::registerMethod("UnregisterPlayer").withInputParamNames("player").implementedAs([this](const sdbus::ObjectPath& player){ return this->UnregisterPlayer(player); })
                          , sdbus::registerMethod("RegisterApplication").withInputParamNames("application", "options").implementedAs([this](const sdbus::ObjectPath& application, const std::map<std::string, sdbus::Variant>& options){ return this->RegisterApplication(application, options); })
                          , sdbus::registerMethod("UnregisterApplication").withInputParamNames("application").implementedAs([this](const sdbus::ObjectPath& application){ return this->UnregisterApplication(application); })
                          , sdbus::registerProperty("SupportedUUIDs").withGetter([this](){ return this->SupportedUUIDs(); })
                          ).forInterface(INTERFACE_NAME);
    }

private:
    virtual void RegisterEndpoint(const sdbus::ObjectPath& endpoint, const std::map<std::string, sdbus::Variant>& properties) = 0;
    virtual void UnregisterEndpoint(const sdbus::ObjectPath& endpoint) = 0;
    virtual void RegisterPlayer(const sdbus::ObjectPath& player, const std::map<std::string, sdbus::Variant>& properties) = 0;
    virtual void UnregisterPlayer(const sdbus::ObjectPath& player) = 0;
    virtual void RegisterApplication(const sdbus::ObjectPath& application, const std::map<std::string, sdbus::Variant>& options) = 0;
    virtual void UnregisterApplication(const sdbus::ObjectPath& application) = 0;

private:
    virtual std::vector<std::string> SupportedUUIDs() = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
