
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_freedesktop_Introspectable_proxy_h__proxy__H__
#define __sdbuscpp__sdbus_org_freedesktop_Introspectable_proxy_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace DBus {

class Introspectable_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.DBus.Introspectable";

protected:
    Introspectable_proxy(sdbus::IProxy& proxy)
        : m_proxy(proxy)
    {
    }

    Introspectable_proxy(const Introspectable_proxy&) = delete;
    Introspectable_proxy& operator=(const Introspectable_proxy&) = delete;
    Introspectable_proxy(Introspectable_proxy&&) = delete;
    Introspectable_proxy& operator=(Introspectable_proxy&&) = delete;

    ~Introspectable_proxy() = default;

    void registerProxy()
    {
    }

public:
    std::string Introspect()
    {
        std::string result;
        m_proxy.callMethod("Introspect").onInterface(INTERFACE_NAME).storeResultsTo(result);
        return result;
    }

private:
    sdbus::IProxy& m_proxy;
};

}}} // namespaces

#endif
