
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_HealthManager1_proxy_h__proxy__H__
#define __sdbuscpp__sdbus_org_bluez_HealthManager1_proxy_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class HealthManager1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.HealthManager1";

protected:
    HealthManager1_proxy(sdbus::IProxy& proxy)
        : m_proxy(proxy)
    {
    }

    HealthManager1_proxy(const HealthManager1_proxy&) = delete;
    HealthManager1_proxy& operator=(const HealthManager1_proxy&) = delete;
    HealthManager1_proxy(HealthManager1_proxy&&) = delete;
    HealthManager1_proxy& operator=(HealthManager1_proxy&&) = delete;

    ~HealthManager1_proxy() = default;

    void registerProxy()
    {
    }

public:
    sdbus::ObjectPath CreateApplication(const std::map<std::string, sdbus::Variant>& config)
    {
        sdbus::ObjectPath result;
        m_proxy.callMethod("CreateApplication").onInterface(INTERFACE_NAME).withArguments(config).storeResultsTo(result);
        return result;
    }

    void DestroyApplication(const sdbus::ObjectPath& application)
    {
        m_proxy.callMethod("DestroyApplication").onInterface(INTERFACE_NAME).withArguments(application);
    }

private:
    sdbus::IProxy& m_proxy;
};

}} // namespaces

#endif
