
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_GattManager1_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_bluez_GattManager1_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class GattManager1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.GattManager1";

protected:
    GattManager1_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    GattManager1_adaptor(const GattManager1_adaptor&) = delete;
    GattManager1_adaptor& operator=(const GattManager1_adaptor&) = delete;
    GattManager1_adaptor(GattManager1_adaptor&&) = delete;
    GattManager1_adaptor& operator=(GattManager1_adaptor&&) = delete;

    ~GattManager1_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("RegisterApplication").withInputParamNames("application", "options").implementedAs([this](const sdbus::ObjectPath& application, const std::map<std::string, sdbus::Variant>& options){ return this->RegisterApplication(application, options); })
                          , sdbus::registerMethod("UnregisterApplication").withInputParamNames("application").implementedAs([this](const sdbus::ObjectPath& application){ return this->UnregisterApplication(application); })
                          ).forInterface(INTERFACE_NAME);
    }

private:
    virtual void RegisterApplication(const sdbus::ObjectPath& application, const std::map<std::string, sdbus::Variant>& options) = 0;
    virtual void UnregisterApplication(const sdbus::ObjectPath& application) = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
