
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_freedesktop_Introspectable_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_freedesktop_Introspectable_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace DBus {

class Introspectable_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.DBus.Introspectable";

protected:
    Introspectable_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    Introspectable_adaptor(const Introspectable_adaptor&) = delete;
    Introspectable_adaptor& operator=(const Introspectable_adaptor&) = delete;
    Introspectable_adaptor(Introspectable_adaptor&&) = delete;
    Introspectable_adaptor& operator=(Introspectable_adaptor&&) = delete;

    ~Introspectable_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable(sdbus::registerMethod("Introspect").withOutputParamNames("xml").implementedAs([this](){ return this->Introspect(); })).forInterface(INTERFACE_NAME);
    }

private:
    virtual std::string Introspect() = 0;

private:
    sdbus::IObject& m_object;
};

}}} // namespaces

#endif
