
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_LEAdvertisement1_proxy_h__proxy__H__
#define __sdbuscpp__sdbus_org_bluez_LEAdvertisement1_proxy_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class LEAdvertisement1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.LEAdvertisement1";

protected:
    LEAdvertisement1_proxy(sdbus::IProxy& proxy)
        : m_proxy(proxy)
    {
    }

    LEAdvertisement1_proxy(const LEAdvertisement1_proxy&) = delete;
    LEAdvertisement1_proxy& operator=(const LEAdvertisement1_proxy&) = delete;
    LEAdvertisement1_proxy(LEAdvertisement1_proxy&&) = delete;
    LEAdvertisement1_proxy& operator=(LEAdvertisement1_proxy&&) = delete;

    ~LEAdvertisement1_proxy() = default;

    void registerProxy()
    {
    }

public:
    void Release()
    {
        m_proxy.callMethod("Release").onInterface(INTERFACE_NAME);
    }

public:
    std::string Type()
    {
        return m_proxy.getProperty("Type").onInterface(INTERFACE_NAME).get<std::string>();
    }

    std::vector<std::string> ServiceUUIDs()
    {
        return m_proxy.getProperty("ServiceUUIDs").onInterface(INTERFACE_NAME).get<std::vector<std::string>>();
    }

    std::map<uint16_t, sdbus::Variant> ManufacturerData()
    {
        return m_proxy.getProperty("ManufacturerData").onInterface(INTERFACE_NAME).get<std::map<uint16_t, sdbus::Variant>>();
    }

    std::vector<std::string> SolicitUUIDs()
    {
        return m_proxy.getProperty("SolicitUUIDs").onInterface(INTERFACE_NAME).get<std::vector<std::string>>();
    }

    std::map<std::string, sdbus::Variant> ServiceData()
    {
        return m_proxy.getProperty("ServiceData").onInterface(INTERFACE_NAME).get<std::map<std::string, sdbus::Variant>>();
    }

    std::map<std::string, sdbus::Variant> Data()
    {
        return m_proxy.getProperty("Data").onInterface(INTERFACE_NAME).get<std::map<std::string, sdbus::Variant>>();
    }

    bool Discoverable()
    {
        return m_proxy.getProperty("Discoverable").onInterface(INTERFACE_NAME).get<bool>();
    }

    void Discoverable(const bool& value)
    {
        m_proxy.setProperty("Discoverable").onInterface(INTERFACE_NAME).toValue(value);
    }

    uint16_t DiscoverableTimeout()
    {
        return m_proxy.getProperty("DiscoverableTimeout").onInterface(INTERFACE_NAME).get<uint16_t>();
    }

    void DiscoverableTimeout(const uint16_t& value)
    {
        m_proxy.setProperty("DiscoverableTimeout").onInterface(INTERFACE_NAME).toValue(value);
    }

    std::vector<std::string> Includes()
    {
        return m_proxy.getProperty("Includes").onInterface(INTERFACE_NAME).get<std::vector<std::string>>();
    }

    std::string LocalName()
    {
        return m_proxy.getProperty("LocalName").onInterface(INTERFACE_NAME).get<std::string>();
    }

    uint16_t Appearance()
    {
        return m_proxy.getProperty("Appearance").onInterface(INTERFACE_NAME).get<uint16_t>();
    }

    uint16_t Duration()
    {
        return m_proxy.getProperty("Duration").onInterface(INTERFACE_NAME).get<uint16_t>();
    }

    uint16_t Timeout()
    {
        return m_proxy.getProperty("Timeout").onInterface(INTERFACE_NAME).get<uint16_t>();
    }

    uint32_t MinInterval()
    {
        return m_proxy.getProperty("MinInterval").onInterface(INTERFACE_NAME).get<uint32_t>();
    }

    uint32_t MaxInterval()
    {
        return m_proxy.getProperty("MaxInterval").onInterface(INTERFACE_NAME).get<uint32_t>();
    }

    int16_t TxPower()
    {
        return m_proxy.getProperty("TxPower").onInterface(INTERFACE_NAME).get<int16_t>();
    }

private:
    sdbus::IProxy& m_proxy;
};

}} // namespaces

#endif
