
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_freedesktop_DBus_ObjectManager_proxy_h__proxy__H__
#define __sdbuscpp__sdbus_org_freedesktop_DBus_ObjectManager_proxy_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace DBus {

class ObjectManager_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.DBus.ObjectManager";

protected:
    ObjectManager_proxy(sdbus::IProxy& proxy)
        : m_proxy(proxy)
    {
    }

    ObjectManager_proxy(const ObjectManager_proxy&) = delete;
    ObjectManager_proxy& operator=(const ObjectManager_proxy&) = delete;
    ObjectManager_proxy(ObjectManager_proxy&&) = delete;
    ObjectManager_proxy& operator=(ObjectManager_proxy&&) = delete;

    ~ObjectManager_proxy() = default;

    void registerProxy()
    {
        m_proxy.uponSignal("InterfacesAdded").onInterface(INTERFACE_NAME).call([this](const sdbus::ObjectPath& object, const std::map<std::string, std::map<std::string, sdbus::Variant>>& interfaces){ this->onInterfacesAdded(object, interfaces); });
        m_proxy.uponSignal("InterfacesRemoved").onInterface(INTERFACE_NAME).call([this](const sdbus::ObjectPath& object, const std::vector<std::string>& interfaces){ this->onInterfacesRemoved(object, interfaces); });
    }

    virtual void onInterfacesAdded(const sdbus::ObjectPath& object, const std::map<std::string, std::map<std::string, sdbus::Variant>>& interfaces) = 0;
    virtual void onInterfacesRemoved(const sdbus::ObjectPath& object, const std::vector<std::string>& interfaces) = 0;

public:
    std::map<sdbus::ObjectPath, std::map<std::string, std::map<std::string, sdbus::Variant>>> GetManagedObjects()
    {
        std::map<sdbus::ObjectPath, std::map<std::string, std::map<std::string, sdbus::Variant>>> result;
        m_proxy.callMethod("GetManagedObjects").onInterface(INTERFACE_NAME).storeResultsTo(result);
        return result;
    }

private:
    sdbus::IProxy& m_proxy;
};

}}} // namespaces

#endif
