
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_freedesktop_DBus_Properties_proxy_h__proxy__H__
#define __sdbuscpp__sdbus_org_freedesktop_DBus_Properties_proxy_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace DBus {

class Properties_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.DBus.Properties";

protected:
    Properties_proxy(sdbus::IProxy& proxy)
        : m_proxy(proxy)
    {
    }

    Properties_proxy(const Properties_proxy&) = delete;
    Properties_proxy& operator=(const Properties_proxy&) = delete;
    Properties_proxy(Properties_proxy&&) = delete;
    Properties_proxy& operator=(Properties_proxy&&) = delete;

    ~Properties_proxy() = default;

    void registerProxy()
    {
        m_proxy.uponSignal("PropertiesChanged").onInterface(INTERFACE_NAME).call([this](const std::string& interface, const std::map<std::string, sdbus::Variant>& changed_properties, const std::vector<std::string>& invalidated_properties){ this->onPropertiesChanged(interface, changed_properties, invalidated_properties); });
    }

    virtual void onPropertiesChanged(const std::string& interface, const std::map<std::string, sdbus::Variant>& changed_properties, const std::vector<std::string>& invalidated_properties) = 0;

public:
    sdbus::Variant Get(const std::string& interface, const std::string& name)
    {
        sdbus::Variant result;
        m_proxy.callMethod("Get").onInterface(INTERFACE_NAME).withArguments(interface, name).storeResultsTo(result);
        return result;
    }

    void Set(const std::string& interface, const std::string& name, const sdbus::Variant& value)
    {
        m_proxy.callMethod("Set").onInterface(INTERFACE_NAME).withArguments(interface, name, value);
    }

    std::map<std::string, sdbus::Variant> GetAll(const std::string& interface)
    {
        std::map<std::string, sdbus::Variant> result;
        m_proxy.callMethod("GetAll").onInterface(INTERFACE_NAME).withArguments(interface).storeResultsTo(result);
        return result;
    }

private:
    sdbus::IProxy& m_proxy;
};

}}} // namespaces

#endif
