
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_BatteryProviderManager_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_bluez_BatteryProviderManager_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class BatteryProviderManager1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.BatteryProviderManager1";

protected:
    BatteryProviderManager1_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    BatteryProviderManager1_adaptor(const BatteryProviderManager1_adaptor&) = delete;
    BatteryProviderManager1_adaptor& operator=(const BatteryProviderManager1_adaptor&) = delete;
    BatteryProviderManager1_adaptor(BatteryProviderManager1_adaptor&&) = delete;
    BatteryProviderManager1_adaptor& operator=(BatteryProviderManager1_adaptor&&) = delete;

    ~BatteryProviderManager1_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("RegisterBatteryProvider").withInputParamNames("provider").implementedAs([this](const sdbus::ObjectPath& provider){ return this->RegisterBatteryProvider(provider); })
                          , sdbus::registerMethod("UnregisterBatteryProvider").withInputParamNames("provider").implementedAs([this](const sdbus::ObjectPath& provider){ return this->UnregisterBatteryProvider(provider); })
                          ).forInterface(INTERFACE_NAME);
    }

private:
    virtual void RegisterBatteryProvider(const sdbus::ObjectPath& provider) = 0;
    virtual void UnregisterBatteryProvider(const sdbus::ObjectPath& provider) = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
