
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_NetworkServer1_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_bluez_NetworkServer1_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class NetworkServer1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.NetworkServer1";

protected:
    NetworkServer1_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    NetworkServer1_adaptor(const NetworkServer1_adaptor&) = delete;
    NetworkServer1_adaptor& operator=(const NetworkServer1_adaptor&) = delete;
    NetworkServer1_adaptor(NetworkServer1_adaptor&&) = delete;
    NetworkServer1_adaptor& operator=(NetworkServer1_adaptor&&) = delete;

    ~NetworkServer1_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("Register").withInputParamNames("uuid", "bridge").implementedAs([this](const std::string& uuid, const std::string& bridge){ return this->Register(uuid, bridge); })
                          , sdbus::registerMethod("Unregister").withInputParamNames("uuid").implementedAs([this](const std::string& uuid){ return this->Unregister(uuid); })
                          ).forInterface(INTERFACE_NAME);
    }

private:
    virtual void Register(const std::string& uuid, const std::string& bridge) = 0;
    virtual void Unregister(const std::string& uuid) = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
