
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_Device1_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_bluez_Device1_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class Device1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.Device1";

protected:
    Device1_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    Device1_adaptor(const Device1_adaptor&) = delete;
    Device1_adaptor& operator=(const Device1_adaptor&) = delete;
    Device1_adaptor(Device1_adaptor&&) = delete;
    Device1_adaptor& operator=(Device1_adaptor&&) = delete;

    ~Device1_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("Disconnect").implementedAs([this](){ return this->Disconnect(); })
                          , sdbus::registerMethod("Connect").implementedAs([this](){ return this->Connect(); })
                          , sdbus::registerMethod("ConnectProfile").withInputParamNames("UUID").implementedAs([this](const std::string& UUID){ return this->ConnectProfile(UUID); })
                          , sdbus::registerMethod("DisconnectProfile").withInputParamNames("UUID").implementedAs([this](const std::string& UUID){ return this->DisconnectProfile(UUID); })
                          , sdbus::registerMethod("Pair").implementedAs([this](){ return this->Pair(); })
                          , sdbus::registerMethod("CancelPairing").implementedAs([this](){ return this->CancelPairing(); })
                          , sdbus::registerProperty("Address").withGetter([this](){ return this->Address(); })
                          , sdbus::registerProperty("AddressType").withGetter([this](){ return this->AddressType(); })
                          , sdbus::registerProperty("Name").withGetter([this](){ return this->Name(); })
                          , sdbus::registerProperty("Alias").withGetter([this](){ return this->Alias(); }).withSetter([this](const std::string& value){ this->Alias(value); })
                          , sdbus::registerProperty("Class").withGetter([this](){ return this->Class(); })
                          , sdbus::registerProperty("Appearance").withGetter([this](){ return this->Appearance(); })
                          , sdbus::registerProperty("Icon").withGetter([this](){ return this->Icon(); })
                          , sdbus::registerProperty("Paired").withGetter([this](){ return this->Paired(); })
                          , sdbus::registerProperty("Bonded").withGetter([this](){ return this->Bonded(); })
                          , sdbus::registerProperty("Trusted").withGetter([this](){ return this->Trusted(); }).withSetter([this](const bool& value){ this->Trusted(value); })
                          , sdbus::registerProperty("Blocked").withGetter([this](){ return this->Blocked(); }).withSetter([this](const bool& value){ this->Blocked(value); })
                          , sdbus::registerProperty("LegacyPairing").withGetter([this](){ return this->LegacyPairing(); })
                          , sdbus::registerProperty("RSSI").withGetter([this](){ return this->RSSI(); })
                          , sdbus::registerProperty("Connected").withGetter([this](){ return this->Connected(); })
                          , sdbus::registerProperty("UUIDs").withGetter([this](){ return this->UUIDs(); })
                          , sdbus::registerProperty("Modalias").withGetter([this](){ return this->Modalias(); })
                          , sdbus::registerProperty("Adapter").withGetter([this](){ return this->Adapter(); })
                          , sdbus::registerProperty("ManufacturerData").withGetter([this](){ return this->ManufacturerData(); })
                          , sdbus::registerProperty("ServiceData").withGetter([this](){ return this->ServiceData(); })
                          , sdbus::registerProperty("TxPower").withGetter([this](){ return this->TxPower(); })
                          , sdbus::registerProperty("ServicesResolved").withGetter([this](){ return this->ServicesResolved(); })
                          , sdbus::registerProperty("WakeAllowed").withGetter([this](){ return this->WakeAllowed(); }).withSetter([this](const bool& value){ this->WakeAllowed(value); })
                          , sdbus::registerProperty("Sets").withGetter([this](){ return this->Sets(); })
                          ).forInterface(INTERFACE_NAME);
    }

private:
    virtual void Disconnect() = 0;
    virtual void Connect() = 0;
    virtual void ConnectProfile(const std::string& UUID) = 0;
    virtual void DisconnectProfile(const std::string& UUID) = 0;
    virtual void Pair() = 0;
    virtual void CancelPairing() = 0;

private:
    virtual std::string Address() = 0;
    virtual std::string AddressType() = 0;
    virtual std::string Name() = 0;
    virtual std::string Alias() = 0;
    virtual void Alias(const std::string& value) = 0;
    virtual uint32_t Class() = 0;
    virtual uint16_t Appearance() = 0;
    virtual std::string Icon() = 0;
    virtual bool Paired() = 0;
    virtual bool Bonded() = 0;
    virtual bool Trusted() = 0;
    virtual void Trusted(const bool& value) = 0;
    virtual bool Blocked() = 0;
    virtual void Blocked(const bool& value) = 0;
    virtual bool LegacyPairing() = 0;
    virtual int16_t RSSI() = 0;
    virtual bool Connected() = 0;
    virtual std::vector<std::string> UUIDs() = 0;
    virtual std::string Modalias() = 0;
    virtual sdbus::ObjectPath Adapter() = 0;
    virtual std::map<uint16_t, sdbus::Variant> ManufacturerData() = 0;
    virtual std::map<std::string, sdbus::Variant> ServiceData() = 0;
    virtual int16_t TxPower() = 0;
    virtual bool ServicesResolved() = 0;
    virtual bool WakeAllowed() = 0;
    virtual void WakeAllowed(const bool& value) = 0;
    virtual std::map<sdbus::ObjectPath, std::map<std::string, sdbus::Variant>> Sets() = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
