
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_freedesktop_DBus_Properties_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_freedesktop_DBus_Properties_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace DBus {

class Properties_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.DBus.Properties";

protected:
    Properties_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    Properties_adaptor(const Properties_adaptor&) = delete;
    Properties_adaptor& operator=(const Properties_adaptor&) = delete;
    Properties_adaptor(Properties_adaptor&&) = delete;
    Properties_adaptor& operator=(Properties_adaptor&&) = delete;

    ~Properties_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("Get").withInputParamNames("interface", "name").withOutputParamNames("value").implementedAs([this](const std::string& interface, const std::string& name){ return this->Get(interface, name); })
                          , sdbus::registerMethod("Set").withInputParamNames("interface", "name", "value").implementedAs([this](const std::string& interface, const std::string& name, const sdbus::Variant& value){ return this->Set(interface, name, value); })
                          , sdbus::registerMethod("GetAll").withInputParamNames("interface").withOutputParamNames("properties").implementedAs([this](const std::string& interface){ return this->GetAll(interface); })
                          , sdbus::registerSignal("PropertiesChanged").withParameters<std::string, std::map<std::string, sdbus::Variant>, std::vector<std::string>>("interface", "changed_properties", "invalidated_properties")
                          ).forInterface(INTERFACE_NAME);
    }

public:
    void emitPropertiesChanged(const std::string& interface, const std::map<std::string, sdbus::Variant>& changed_properties, const std::vector<std::string>& invalidated_properties)
    {
        m_object.emitSignal("PropertiesChanged").onInterface(INTERFACE_NAME).withArguments(interface, changed_properties, invalidated_properties);
    }

private:
    virtual sdbus::Variant Get(const std::string& interface, const std::string& name) = 0;
    virtual void Set(const std::string& interface, const std::string& name, const sdbus::Variant& value) = 0;
    virtual std::map<std::string, sdbus::Variant> GetAll(const std::string& interface) = 0;

private:
    sdbus::IObject& m_object;
};

}}} // namespaces

#endif
