
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_AgentManager1_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_bluez_AgentManager1_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class AgentManager1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.AgentManager1";

protected:
    AgentManager1_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    AgentManager1_adaptor(const AgentManager1_adaptor&) = delete;
    AgentManager1_adaptor& operator=(const AgentManager1_adaptor&) = delete;
    AgentManager1_adaptor(AgentManager1_adaptor&&) = delete;
    AgentManager1_adaptor& operator=(AgentManager1_adaptor&&) = delete;

    ~AgentManager1_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("RegisterAgent").withInputParamNames("agent", "capability").implementedAs([this](const sdbus::ObjectPath& agent, const std::string& capability){ return this->RegisterAgent(agent, capability); })
                          , sdbus::registerMethod("UnregisterAgent").withInputParamNames("agent").implementedAs([this](const sdbus::ObjectPath& agent){ return this->UnregisterAgent(agent); })
                          , sdbus::registerMethod("RequestDefaultAgent").withInputParamNames("agent").implementedAs([this](const sdbus::ObjectPath& agent){ return this->RequestDefaultAgent(agent); })
                          ).forInterface(INTERFACE_NAME);
    }

private:
    virtual void RegisterAgent(const sdbus::ObjectPath& agent, const std::string& capability) = 0;
    virtual void UnregisterAgent(const sdbus::ObjectPath& agent) = 0;
    virtual void RequestDefaultAgent(const sdbus::ObjectPath& agent) = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
