
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_Battery1_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_bluez_Battery1_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class Battery1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.Battery1";

protected:
    Battery1_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    Battery1_adaptor(const Battery1_adaptor&) = delete;
    Battery1_adaptor& operator=(const Battery1_adaptor&) = delete;
    Battery1_adaptor(Battery1_adaptor&&) = delete;
    Battery1_adaptor& operator=(Battery1_adaptor&&) = delete;

    ~Battery1_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerProperty("Percentage").withGetter([this](){ return this->Percentage(); })
                          , sdbus::registerProperty("Source").withGetter([this](){ return this->Source(); })
                          ).forInterface(INTERFACE_NAME);
    }

private:
    virtual uint8_t Percentage() = 0;
    virtual std::string Source() = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
