
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_GattCharacteristic1_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_bluez_GattCharacteristic1_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class GattCharacteristic1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.GattCharacteristic1";

protected:
    GattCharacteristic1_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    GattCharacteristic1_adaptor(const GattCharacteristic1_adaptor&) = delete;
    GattCharacteristic1_adaptor& operator=(const GattCharacteristic1_adaptor&) = delete;
    GattCharacteristic1_adaptor(GattCharacteristic1_adaptor&&) = delete;
    GattCharacteristic1_adaptor& operator=(GattCharacteristic1_adaptor&&) = delete;

    ~GattCharacteristic1_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("ReadValue").withInputParamNames("options").withOutputParamNames("value").implementedAs([this](const std::map<std::string, sdbus::Variant>& options){ return this->ReadValue(options); })
                          , sdbus::registerMethod("WriteValue").withInputParamNames("value", "options").implementedAs([this](const std::vector<uint8_t>& value, const std::map<std::string, sdbus::Variant>& options){ return this->WriteValue(value, options); })
                          , sdbus::registerMethod("AcquireWrite").withInputParamNames("options").withOutputParamNames("fd", "mtu").implementedAs([this](const std::map<std::string, sdbus::Variant>& options){ return this->AcquireWrite(options); })
                          , sdbus::registerMethod("AcquireNotify").withInputParamNames("options").withOutputParamNames("fd", "mtu").implementedAs([this](const std::map<std::string, sdbus::Variant>& options){ return this->AcquireNotify(options); })
                          , sdbus::registerMethod("StartNotify").implementedAs([this](){ return this->StartNotify(); })
                          , sdbus::registerMethod("StopNotify").implementedAs([this](){ return this->StopNotify(); })
                          , sdbus::registerProperty("Handle").withGetter([this](){ return this->Handle(); })
                          , sdbus::registerProperty("UUID").withGetter([this](){ return this->UUID(); })
                          , sdbus::registerProperty("Service").withGetter([this](){ return this->Service(); })
                          , sdbus::registerProperty("Value").withGetter([this](){ return this->Value(); })
                          , sdbus::registerProperty("Notifying").withGetter([this](){ return this->Notifying(); })
                          , sdbus::registerProperty("Flags").withGetter([this](){ return this->Flags(); })
                          , sdbus::registerProperty("WriteAcquired").withGetter([this](){ return this->WriteAcquired(); })
                          , sdbus::registerProperty("NotifyAcquired").withGetter([this](){ return this->NotifyAcquired(); })
                          , sdbus::registerProperty("MTU").withGetter([this](){ return this->MTU(); })
                          ).forInterface(INTERFACE_NAME);
    }

private:
    virtual std::vector<uint8_t> ReadValue(const std::map<std::string, sdbus::Variant>& options) = 0;
    virtual void WriteValue(const std::vector<uint8_t>& value, const std::map<std::string, sdbus::Variant>& options) = 0;
    virtual std::tuple<sdbus::UnixFd, uint16_t> AcquireWrite(const std::map<std::string, sdbus::Variant>& options) = 0;
    virtual std::tuple<sdbus::UnixFd, uint16_t> AcquireNotify(const std::map<std::string, sdbus::Variant>& options) = 0;
    virtual void StartNotify() = 0;
    virtual void StopNotify() = 0;

private:
    virtual uint16_t Handle() = 0;
    virtual std::string UUID() = 0;
    virtual sdbus::ObjectPath Service() = 0;
    virtual std::vector<uint8_t> Value() = 0;
    virtual bool Notifying() = 0;
    virtual std::vector<std::string> Flags() = 0;
    virtual bool WriteAcquired() = 0;
    virtual bool NotifyAcquired() = 0;
    virtual uint16_t MTU() = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
