
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__sdbus_org_bluez_Adapter1_adaptor_h__adaptor__H__
#define __sdbuscpp__sdbus_org_bluez_Adapter1_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class Adapter1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.Adapter1";

protected:
    Adapter1_adaptor(sdbus::IObject& object)
        : m_object(object)
    {
    }

    Adapter1_adaptor(const Adapter1_adaptor&) = delete;
    Adapter1_adaptor& operator=(const Adapter1_adaptor&) = delete;
    Adapter1_adaptor(Adapter1_adaptor&&) = delete;
    Adapter1_adaptor& operator=(Adapter1_adaptor&&) = delete;

    ~Adapter1_adaptor() = default;

    void registerAdaptor()
    {
        m_object.addVTable( sdbus::registerMethod("StartDiscovery").implementedAs([this](){ return this->StartDiscovery(); })
                          , sdbus::registerMethod("SetDiscoveryFilter").withInputParamNames("properties").implementedAs([this](const std::map<std::string, sdbus::Variant>& properties){ return this->SetDiscoveryFilter(properties); })
                          , sdbus::registerMethod("StopDiscovery").implementedAs([this](){ return this->StopDiscovery(); })
                          , sdbus::registerMethod("RemoveDevice").withInputParamNames("device").implementedAs([this](const sdbus::ObjectPath& device){ return this->RemoveDevice(device); })
                          , sdbus::registerMethod("GetDiscoveryFilters").withOutputParamNames("filters").implementedAs([this](){ return this->GetDiscoveryFilters(); })
                          , sdbus::registerProperty("Address").withGetter([this](){ return this->Address(); })
                          , sdbus::registerProperty("AddressType").withGetter([this](){ return this->AddressType(); })
                          , sdbus::registerProperty("Name").withGetter([this](){ return this->Name(); })
                          , sdbus::registerProperty("Alias").withGetter([this](){ return this->Alias(); }).withSetter([this](const std::string& value){ this->Alias(value); })
                          , sdbus::registerProperty("Class").withGetter([this](){ return this->Class(); })
                          , sdbus::registerProperty("Powered").withGetter([this](){ return this->Powered(); }).withSetter([this](const bool& value){ this->Powered(value); })
                          , sdbus::registerProperty("Discoverable").withGetter([this](){ return this->Discoverable(); }).withSetter([this](const bool& value){ this->Discoverable(value); })
                          , sdbus::registerProperty("DiscoverableTimeout").withGetter([this](){ return this->DiscoverableTimeout(); }).withSetter([this](const uint32_t& value){ this->DiscoverableTimeout(value); })
                          , sdbus::registerProperty("Pairable").withGetter([this](){ return this->Pairable(); }).withSetter([this](const bool& value){ this->Pairable(value); })
                          , sdbus::registerProperty("PairableTimeout").withGetter([this](){ return this->PairableTimeout(); }).withSetter([this](const uint32_t& value){ this->PairableTimeout(value); })
                          , sdbus::registerProperty("Discovering").withGetter([this](){ return this->Discovering(); })
                          , sdbus::registerProperty("UUIDs").withGetter([this](){ return this->UUIDs(); })
                          , sdbus::registerProperty("Modalias").withGetter([this](){ return this->Modalias(); })
                          , sdbus::registerProperty("Roles").withGetter([this](){ return this->Roles(); })
                          , sdbus::registerProperty("ExperimentalFeatures").withGetter([this](){ return this->ExperimentalFeatures(); })
                          , sdbus::registerProperty("Manufacturer").withGetter([this](){ return this->Manufacturer(); })
                          , sdbus::registerProperty("Version").withGetter([this](){ return this->Version(); })
                          ).forInterface(INTERFACE_NAME);
    }

private:
    virtual void StartDiscovery() = 0;
    virtual void SetDiscoveryFilter(const std::map<std::string, sdbus::Variant>& properties) = 0;
    virtual void StopDiscovery() = 0;
    virtual void RemoveDevice(const sdbus::ObjectPath& device) = 0;
    virtual std::vector<std::string> GetDiscoveryFilters() = 0;

private:
    virtual std::string Address() = 0;
    virtual std::string AddressType() = 0;
    virtual std::string Name() = 0;
    virtual std::string Alias() = 0;
    virtual void Alias(const std::string& value) = 0;
    virtual uint32_t Class() = 0;
    virtual bool Powered() = 0;
    virtual void Powered(const bool& value) = 0;
    virtual bool Discoverable() = 0;
    virtual void Discoverable(const bool& value) = 0;
    virtual uint32_t DiscoverableTimeout() = 0;
    virtual void DiscoverableTimeout(const uint32_t& value) = 0;
    virtual bool Pairable() = 0;
    virtual void Pairable(const bool& value) = 0;
    virtual uint32_t PairableTimeout() = 0;
    virtual void PairableTimeout(const uint32_t& value) = 0;
    virtual bool Discovering() = 0;
    virtual std::vector<std::string> UUIDs() = 0;
    virtual std::string Modalias() = 0;
    virtual std::vector<std::string> Roles() = 0;
    virtual std::vector<std::string> ExperimentalFeatures() = 0;
    virtual uint16_t Manufacturer() = 0;
    virtual uint8_t Version() = 0;

private:
    sdbus::IObject& m_object;
};

}} // namespaces

#endif
