name: Coverity Full Analysis Scan

on:
  push:
    branches: [ develop ]
    paths: ['**/*.c', '**/*.cpp', '**/*.cc', '**/*.cxx', '**/*.h', '**/*.hpp']

jobs:
  call_coverity_full_scan:
    uses: rdk-common/build_tools_workflows/.github/workflows/coverity_component_full_scan.yml@develop
    with:
      branchName: ${{ github.ref_name }}
      # Specify your actual build command here
      buildCommand: bash build.sh
      customSetup: apt-get update -y && apt-get install -y libjsonrpccpp-dev autoconf automake libtool