permissions:
  contents: read
name: main-workflow

on:
  push:
    branches: [ main, develop, 'sprint/**', 'release/**', 'topic/top-plugin' ]
  pull_request:
    branches: [ main, develop, 'sprint/**', 'release/**', 'topic/top-plugin' ]

jobs:
  trigger-L2:
    uses: ./.github/workflows/L2-tests.yml
    secrets: inherit
    with:
      caller_source: local
      
  trigger-L1:
    uses: ./.github/workflows/L1-tests.yml
    with:
      caller_source: local